SELECT DISTINCT
    PRODUCT_CODE,
    SUM(PRICE * SALES_AMOUNT) AS SALES
FROM
    OFFLINE_SALE
JOIN
    PRODUCT
USING (PRODUCT_ID)
GROUP BY
    PRODUCT_ID
ORDER BY
    SALES DESC,
    PRODUCT_CODE ASC;