SELECT
    C.ID,
    C.GENOTYPE,
    P.GENOTYPE AS "PARENT_GENOTYPE"
FROM
    ECOLI_DATA C
JOIN
    ECOLI_DATA P
WHERE
    C.PARENT_ID = P.ID
    AND
    C.GENOTYPE & P.GENOTYPE = P.GENOTYPE
ORDER BY
    C.ID