/*
    연도별 SIZE_OF_COLONY의 MAX값을 MAX_SIZE로
    DIFFERENTIATION_DATE에서의 YEAR 값을 YEAR로
    갖는 YearlyMaxSize TABLE을 y로 LEFT JOIN해서 
*/


WITH 
    YearlyMaxSize AS (
        SELECT 
            EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR,
            MAX(SIZE_OF_COLONY) AS MAX_SIZE
        FROM 
            ECOLI_DATA
        GROUP BY 
            EXTRACT(YEAR FROM DIFFERENTIATION_DATE)
    )
SELECT 
    EXTRACT(YEAR FROM e.DIFFERENTIATION_DATE) AS YEAR,
    y.MAX_SIZE - e.SIZE_OF_COLONY AS YEAR_DEV,
    e.ID
FROM 
    ECOLI_DATA e
JOIN 
    YearlyMaxSize y 
ON 
    EXTRACT(YEAR FROM e.DIFFERENTIATION_DATE) = y.YEAR
ORDER BY 
    YEAR ASC,
    YEAR_DEV ASC