SELECT
    a.FLAVOR
FROM
    FIRST_HALF AS a
JOIN
    ICECREAM_INFO AS b
ON
    a.FLAVOR = b.FLAVOR
WHERE
    a.TOTAL_ORDER >= 3000
    AND
    b.INGREDIENT_TYPE LIKE 'fruit_based'
ORDER BY
    TOTAL_ORDER DESC